name: pangeo
channels:
 - pytorch
 - conda-forge
dependencies:
 - python=3.8*
 - pangeo-notebook=2021.08.04
 - pip=20
 - pytorch::pytorch
 - pytorch::torchvision
 - pytorch::torchaudio
 - cudatoolkit>=11,<12
 - efficientnet-pytorch=0.6.3
 - rasterio
 - timm
 - matplotlib-base
 - adlfs>=0.5.9
 - xarray
 - jupyterlab-nvdashboard
 # https://github.com/holoviz/hvplot/issues/576
 - hvplot==0.7.0
 - datashader
 - numpy
 - stac-vrt
 - rioxarray
 - planetary-computer>=0.2.2
 - pystac-client>=0.2.0
 - pystac>=1.1.0
 - numba>=0.53.1
 # Install pre-release from PYPI
 - pretrainedmodels==0.7.4
 - segmentation-models-pytorch
 - shapely
 - ipyleaflet
 - scikit-learn
 # For some reason, dask-cuda from conda-forge is causing issues. I haven't debugged yet.
 # - dask-cuda>=21.6.0
