name: Build
on:
  push:
    branches:
      - main

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        # IMAGE: [python, r, gpu-pytorch]
        IMAGE: [test]

    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    on:
      push:
        paths:
          - "{{ matrix.IMAGE }}"

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check for changes
      id: changes
      run: |
        if ! git diff --quiet HEAD~ -- ${{ matrix.IMAGE }}; then
          echo "::set-output name=build::true"
        else
          echo "::set-output name=build::false"
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      if: ${{ steps.changes.outputs.build == "true" }}

    - name: Docker login
      run:
        docker login pcccr.azurecr.io --username ${{ secrets.AZURE_CLIENT_ID}} --password ${{ secrets.AZURE_CLIENT_SECRET }}
      if: ${{ steps.changes.outputs.build == "true" }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        context: ${{ matrix.IMAGE }}
        tags: pcccr.azurecr.io/public/microsoft/planetary-computer/${{ matrix.IMAGE }}:latest
      if: ${{ steps.changes.outputs.build == "true" }}

